# -*- coding: utf-8 -*-
"""
Minecraft modlari ma'lumotlar bazasi (100 ta mod, 11 kategoriya).
API yoki tashqi kalit talab qilinmaydi — hammasi qo'lda kiritilgan,
haqiqiy va tekshirilgan modlar.
"""

MODS = {
    "optimizatsiya": {
        "title": "⚡ Optimallashtirish",
        "mods": [
            {"name": "OptiFine", "desc": "O'yin unumdorligini oshiradi, shaderlar va HD teksturalarni qo'llab-quvvatlaydi.", "link": "https://optifine.net"},
            {"name": "Sodium", "desc": "Fabric uchun render tezligini sezilarli darajada oshiruvchi mod.", "link": "https://modrinth.com/mod/sodium"},
            {"name": "Lithium", "desc": "O'yin logikasini optimallashtirib, TPS (tick rate)ni yaxshilaydi.", "link": "https://modrinth.com/mod/lithium"},
            {"name": "Phosphor", "desc": "Yorug'lik hisob-kitoblarini optimallashtirib, FPS oshiradi.", "link": "https://modrinth.com/mod/phosphor"},
            {"name": "FerriteCore", "desc": "Xotira (RAM) sarfini kamaytiradi.", "link": "https://modrinth.com/mod/ferrite-core"},
            {"name": "Starlight", "desc": "Yorug'lik dvigatelini to'liq qayta yozib, yuklanish tezligini oshiradi.", "link": "https://modrinth.com/mod/starlight"},
            {"name": "ModernFix", "desc": "Yuklanish vaqtini va xotira sarfini kamaytiruvchi keng qamrovli optimallashtirish.", "link": "https://modrinth.com/mod/modernfix"},
            {"name": "EntityCulling", "desc": "Ko'rinmas mahluq va blok renderlarini o'chirib, FPS oshiradi.", "link": "https://modrinth.com/mod/entityculling"},
            {"name": "ImmediatelyFast", "desc": "Render jarayonini tezlashtiruvchi yengil optimallashtirish moduli.", "link": "https://modrinth.com/mod/immediatelyfast"},
            {"name": "Krypton", "desc": "Tarmoq (network) protokoli ishlashini optimallashtiradi.", "link": "https://modrinth.com/mod/krypton"},
            {"name": "Clumps", "desc": "Yerdagi tajriba (XP) sharlarini birlashtirib, lag'ni kamaytiradi.", "link": "https://modrinth.com/mod/clumps"},
            {"name": "Dynamic FPS", "desc": "O'yin fonda (minimallashtirilganda) protsessor yukini keskin kamaytiradi.", "link": "https://modrinth.com/mod/dynamic-fps"},
            {"name": "Sodium Extra", "desc": "Sodium modiga qo'shimcha sozlash va optimallashtirish imkoniyatlari qo'shadi.", "link": "https://modrinth.com/mod/sodium-extra"},
        ],
    },
    "grafika": {
        "title": "🎨 Grafika va Shaderlar",
        "mods": [
            {"name": "Iris Shaders", "desc": "Fabric uchun zamonaviy shader yuklovchi, Sodium bilan mos ishlaydi.", "link": "https://modrinth.com/mod/iris"},
            {"name": "BSL Shaders", "desc": "Realistik yorug'lik, soya va suv effektlarini qo'shadi.", "link": "https://www.curseforge.com/minecraft/customization/bsl-shaders"},
            {"name": "Complementary Shaders", "desc": "Yengil va chiroyli, ko'p qurilmalarda yaxshi ishlaydigan shader.", "link": "https://modrinth.com/shader/complementary-reimagined"},
            {"name": "SEUS", "desc": "Kino sifatidagi yorug'lik va soyalar bilan mashhur shader to'plami.", "link": "https://sonicether.com/shaders/"},
            {"name": "Chocapic13 Shaders", "desc": "Sozlash imkoniyati keng bo'lgan mashhur shader to'plami.", "link": "https://www.curseforge.com/minecraft/customization/chocapic13"},
            {"name": "Sildur's Vibrant Shaders", "desc": "Yorqin ranglar va yuqori unumdorlik o'rtasida muvozanat saqlagan shader.", "link": "https://sildurs-shaders.github.io/"},
            {"name": "Continuum Shaders", "desc": "Fotoreal darajadagi yorug'lik va aks etish effektlari bilan premium shader.", "link": "https://www.complementary.dev/continuum/"},
            {"name": "Better Foliage", "desc": "Daraxt va o'simliklarni zichroq va tabiiyroq ko'rinishga keltiradi.", "link": "https://modrinth.com/mod/better-foliage"},
            {"name": "3D Skin Layers", "desc": "O'yinchi terisining ikkinchi qatlamini (kiyim, soch) 3D qilib ko'rsatadi.", "link": "https://modrinth.com/mod/3d-skin-layers"},
            {"name": "Fresh Animations", "desc": "Mahluqlar uchun yangi, jonli va sifatli animatsiyalarni qo'shadigan resurs to'plami.", "link": "https://modrinth.com/resourcepack/fresh-animations"},
        ],
    },
    "texnika": {
        "title": "⚙️ Texnika va Avtomatlashtirish",
        "mods": [
            {"name": "Create", "desc": "Mexanik dastgohlar, konveyerlar va avtomatlashtirish tizimlarini qo'shadi.", "link": "https://modrinth.com/mod/create"},
            {"name": "Industrial Craft 2 (IC2)", "desc": "Elektr energiyasi, reaktorlar va sanoat mashinalarini qo'shadi.", "link": "https://www.curseforge.com/minecraft/mc-mods/industrial-craft"},
            {"name": "Applied Energistics 2 (AE2)", "desc": "Raqamli ombor va avtomatlashtirilgan buyumlarni saqlash tizimi.", "link": "https://modrinth.com/mod/ae2"},
            {"name": "Thermal Expansion", "desc": "Energiya ishlab chiqarish va mashinalar to'plami.", "link": "https://www.curseforge.com/minecraft/mc-mods/thermal-expansion"},
            {"name": "Mekanism", "desc": "Yadro energiyasi, kimyoviy jarayonlar va yuqori darajali mashinalarni qo'shadi.", "link": "https://modrinth.com/mod/mekanism"},
            {"name": "Refined Storage", "desc": "Modulli va kengaytiriladigan raqamli saqlash tizimi.", "link": "https://modrinth.com/mod/refined-storage"},
            {"name": "Immersive Engineering", "desc": "Real hayotga o'xshash og'ir sanoat mashinalari va elektr liniyalari.", "link": "https://modrinth.com/mod/immersive-engineering"},
            {"name": "ProjectE", "desc": "EMC energiyasi orqali buyumlarni bir-biriga aylantirish tizimi.", "link": "https://www.curseforge.com/minecraft/mc-mods/projecte"},
            {"name": "Storage Drawers", "desc": "Buyumlarni tartibli saqlash uchun ko'rinadigan tortmalar qo'shadi.", "link": "https://modrinth.com/mod/storage-drawers"},
            {"name": "Modular Routers", "desc": "Buyumlarni avtomatik tashish va saralash uchun modulli qurilmalar.", "link": "https://www.curseforge.com/minecraft/mc-mods/modular-routers"},
            {"name": "Extreme Reactors", "desc": "Katta hajmdagi kuchli energiya reaktorlarini qo'shadi.", "link": "https://www.curseforge.com/minecraft/mc-mods/extreme-reactors"},
            {"name": "Powah", "desc": "Zamonaviy energiya ishlab chiqarish va saqlash tizimi.", "link": "https://modrinth.com/mod/powah"},
            {"name": "Pipez", "desc": "Buyum, suyuqlik va energiyani tashish uchun sodda quvurlarni qo'shadi.", "link": "https://www.curseforge.com/minecraft/mc-mods/pipez"},
            {"name": "Simple Storage Network", "desc": "Sandiqlarni tarmoqqa ulab, yagona qidiruv tizimida boshqarish imkonini beradi.", "link": "https://www.curseforge.com/minecraft/mc-mods/simple-storage-network"},
            {"name": "PneumaticCraft: Repressurized", "desc": "Bosim (havo) energiyasiga asoslangan noyob avtomatlashtirish tizimi.", "link": "https://www.curseforge.com/minecraft/mc-mods/pneumaticcraft-repressurized"},
        ],
    },
    "sarguzasht": {
        "title": "🗺️ Sarguzasht va Yangi Dunyolar",
        "mods": [
            {"name": "Biomes O' Plenty", "desc": "O'yinga 90 dan ortiq yangi biomlarni qo'shadi.", "link": "https://modrinth.com/mod/biomesoplenty"},
            {"name": "Twilight Forest", "desc": "Sirli o'rmon o'lchovi, boss janglar va topishmoqlar bilan.", "link": "https://modrinth.com/mod/twilightforest"},
            {"name": "The Aether", "desc": "Osmon ustidagi jannat o'lchovini qo'shadi.", "link": "https://modrinth.com/mod/aether"},
            {"name": "Mowzie's Mobs", "desc": "Noyob va kuchli yangi mahluqlarni qo'shadi.", "link": "https://www.curseforge.com/minecraft/mc-mods/mowzies-mobs"},
            {"name": "The Betweenlands", "desc": "Botqoqli, sirli va qorong'u yangi o'lchovni qo'shadi.", "link": "https://www.curseforge.com/minecraft/mc-mods/the-betweenlands"},
            {"name": "Undergarden", "desc": "Yer osti dunyosidagi g'alati o'simlik va mahluqlar bilan to'la o'lchov.", "link": "https://modrinth.com/mod/undergarden"},
            {"name": "Alex's Caves", "desc": "Yerto'la (cave) tizimlariga yangi noyob joylar va mahluqlarni qo'shadi.", "link": "https://modrinth.com/mod/alexs-caves"},
            {"name": "Blue Skies", "desc": "Ikkita yangi go'zal o'lchov — Everbright va Everdawn'ni qo'shadi.", "link": "https://modrinth.com/mod/blue-skies"},
            {"name": "Terralith", "desc": "Vanilla dunyo generatsiyasiga ko'plab yangi relyef va biomlar qo'shadi.", "link": "https://modrinth.com/mod/terralith"},
            {"name": "Yung's Better Dungeons", "desc": "Vanilla temir devor qal'alarini yaxshilangan, ko'proq mazmunli qilib qayta yaratadi.", "link": "https://modrinth.com/mod/yungs-better-dungeons"},
            {"name": "Alex's Mobs", "desc": "50 dan ortiq noyob va real hayvonlarga o'xshash mahluqlarni qo'shadi.", "link": "https://modrinth.com/mod/alexsmobs"},
            {"name": "Ice and Fire: Dragons", "desc": "Ajdarholar, mifologik mahluqlar va ularning ov qurollarini qo'shadi.", "link": "https://www.curseforge.com/minecraft/mc-mods/ice-and-fire-dragons"},
            {"name": "When Dungeons Arise", "desc": "Dunyoga yangi, batafsil ishlangan zindon va qal'a inshootlarini qo'shadi.", "link": "https://modrinth.com/mod/when-dungeons-arise"},
            {"name": "Repurposed Structures", "desc": "Vanilla inshootlarni yangi biomlarga moslashtirib qayta yaratadi.", "link": "https://modrinth.com/mod/repurposed-structures"},
            {"name": "Yung's Better Mineshafts", "desc": "Kon yo'llarini turli biomga mos, yaxshilangan dizaynda qayta quradi.", "link": "https://modrinth.com/mod/yungs-better-mineshafts"},
        ],
    },
    "qulaylik": {
        "title": "🧰 Qulaylik va Interfeys",
        "mods": [
            {"name": "JEI (Just Enough Items)", "desc": "Barcha buyum va retseptlarni tez ko'rish imkonini beradi.", "link": "https://modrinth.com/mod/jei"},
            {"name": "Waystones", "desc": "Tez sayohat qilish uchun teleport toshlarini qo'shadi.", "link": "https://modrinth.com/mod/waystones"},
            {"name": "JourneyMap", "desc": "Real vaqtda xarita va minimapni ko'rsatadi.", "link": "https://modrinth.com/mod/journeymap"},
            {"name": "Inventory Tweaks", "desc": "Yukxonani avtomatik tartiblash va saralashni osonlashtiradi.", "link": "https://www.curseforge.com/minecraft/mc-mods/inventory-tweaks"},
            {"name": "Xaero's Minimap", "desc": "Yengil va sozlanuvchi minimap ekranning burchagida ko'rsatiladi.", "link": "https://modrinth.com/mod/xaeros-minimap"},
            {"name": "Xaero's World Map", "desc": "To'liq ekranli, batafsil dunyo xaritasini qo'shadi.", "link": "https://modrinth.com/mod/xaeros-world-map"},
            {"name": "AppleSkin", "desc": "Ochlik va to'yinganlik haqida qo'shimcha ma'lumotlarni ko'rsatadi.", "link": "https://modrinth.com/mod/appleskin"},
            {"name": "Mouse Tweaks", "desc": "Sichqoncha bilan yukxonada buyumlarni tezroq boshqarish imkonini beradi.", "link": "https://modrinth.com/mod/mouse-tweaks"},
            {"name": "REI (Roughly Enough Items)", "desc": "JEI'ga o'xshash, Fabric uchun mashhur retsept ko'rish moduli.", "link": "https://modrinth.com/mod/rei"},
            {"name": "EMI", "desc": "Tez va yengil retsept ko'rish interfeysi.", "link": "https://modrinth.com/mod/emi"},
            {"name": "Controlling", "desc": "Klaviatura tugmalarini qidirish va boshqarishni osonlashtiradi.", "link": "https://www.curseforge.com/minecraft/mc-mods/controlling"},
            {"name": "Sound Physics Remastered", "desc": "Ovoz effektlariga realistik aks-sado va xona akustikasini qo'shadi.", "link": "https://modrinth.com/mod/sound-physics-remastered"},
            {"name": "Not Enough Animations", "desc": "O'yinchining o'tirish, sirg'anish kabi harakatlariga yangi animatsiyalar qo'shadi.", "link": "https://modrinth.com/mod/not-enough-animations"},
            {"name": "Zoomify", "desc": "Tugma bosib, kamerani vaqtincha yaqinlashtirish (zoom) imkonini beradi.", "link": "https://modrinth.com/mod/zoomify"},
            {"name": "Better Third Person", "desc": "Uchinchi shaxs kamera burchagini yaxshilaydi va sozlash imkonini beradi.", "link": "https://modrinth.com/mod/better-third-person"},
        ],
    },
    "kamera": {
        "title": "📷 Kamera va Suratga olish",
        "mods": [
            {"name": "Camera Mod", "desc": "O'yin ichida ishlaydigan kamera bilan surat oling va devorga rasm qilib osing.", "link": "https://www.curseforge.com/minecraft/mc-mods/camera-mod"},
            {"name": "Camerapture", "desc": "Kamera bilan surat olib, boshqa o'yinchilarga ko'rsating va devorga ilib qo'ying.", "link": "https://www.curseforge.com/minecraft/mc-mods/camerapture"},
        ],
    },
    "sehr_jodu": {
        "title": "🔮 Sehr-jodu",
        "mods": [
            {"name": "Ars Nouveau", "desc": "O'z sehr-jodularingizni yaratish imkonini beruvchi chuqur magiya tizimi.", "link": "https://modrinth.com/mod/ars-nouveau"},
            {"name": "Botania", "desc": "Tabiat kuchidan foydalangan holda o'ziga xos magiya va texnika tizimi.", "link": "https://modrinth.com/mod/botania"},
            {"name": "Astral Sorcery", "desc": "Yulduzlar va osmon jismlari kuchidan foydalanuvchi magiya mod.", "link": "https://www.curseforge.com/minecraft/mc-mods/astral-sorcery"},
            {"name": "Iron's Spells 'n Spellbooks", "desc": "Ko'plab yangi sehr-jodular va sehrgarlik klassi elementlarini qo'shadi.", "link": "https://modrinth.com/mod/irons-spells-n-spellbooks"},
            {"name": "Origins", "desc": "O'yinchiga turli irqiy qobiliyatlar (kelib chiqishlar) tanlash imkonini beradi.", "link": "https://modrinth.com/mod/origins"},
            {"name": "Trinkets", "desc": "Uzuk, amulet kabi qo'shimcha kiyinish joylarini qo'shadigan API mod.", "link": "https://modrinth.com/mod/trinkets"},
            {"name": "Curios API", "desc": "Modlar uchun qo'shimcha kiyim/aksessuar joylarini yaratish tizimi.", "link": "https://www.curseforge.com/minecraft/mc-mods/curios"},
            {"name": "Bewitchment", "desc": "Jodugarlik, marosimlar va oy fazalariga asoslangan magiya tizimi.", "link": "https://www.curseforge.com/minecraft/mc-mods/bewitchment"},
            {"name": "Blood Magic", "desc": "Qon va qurbonlik orqali kuch olinadigan mashhur qorong'u magiya tizimi.", "link": "https://www.curseforge.com/minecraft/mc-mods/blood-magic"},
        ],
    },
    "jangovar": {
        "title": "⚔️ Jangovar va Qurollar",
        "mods": [
            {"name": "Epic Fight Mod", "desc": "Jangovar tizimni butunlay o'zgartirib, animatsiyali kombolarni qo'shadi.", "link": "https://modrinth.com/mod/epic-fight-mod"},
            {"name": "MrCrayfish's Gun Mod", "desc": "Zamonaviy o'q otar qurollarni Minecraft'ga olib kiradi.", "link": "https://www.curseforge.com/minecraft/mc-mods/mrcrayfishs-gun-mod"},
            {"name": "Better Combat", "desc": "Jang animatsiyalari va mexanikasini yaxshilaydi.", "link": "https://modrinth.com/mod/better-combat"},
            {"name": "Bullseye", "desc": "Kamon va boshqa uzoq masofali qurollarni kengaytiradi.", "link": "https://www.curseforge.com/minecraft/mc-mods/bullseye"},
            {"name": "L_Ender's Cataclysm", "desc": "Kuchli yangi boss janglar va epik qurollarni qo'shadi.", "link": "https://www.curseforge.com/minecraft/mc-mods/cataclysm"},
            {"name": "Spartan Weaponry", "desc": "Nayza, bolta, kalxon kabi ko'plab yangi qurol turlarini qo'shadi.", "link": "https://www.curseforge.com/minecraft/mc-mods/spartan-weaponry"},
        ],
    },
    "fermerlik": {
        "title": "🌾 Qishloq xo'jaligi va Pazandachilik",
        "mods": [
            {"name": "Farmer's Delight", "desc": "Yangi ekinlar, ovqatlar va oshxona jihozlarini qo'shadi.", "link": "https://modrinth.com/mod/farmers-delight"},
            {"name": "Pam's HarvestCraft 2", "desc": "Ko'plab yangi ekinlar, mevalar va retseptlarni qo'shadi.", "link": "https://www.curseforge.com/minecraft/mc-mods/pams-harvestcraft-2-rebased"},
            {"name": "Croptopia", "desc": "Real dunyodagi ekinlar va taomlarni o'yinga olib kiradi.", "link": "https://modrinth.com/mod/croptopia"},
            {"name": "Cooking for Blockheads", "desc": "Oshxonada ovqat tayyorlashni ancha qulaylashtiradi.", "link": "https://modrinth.com/mod/cooking-for-blockheads"},
            {"name": "Delightful", "desc": "Farmer's Delight moduliga ko'plab yangi ekin va taomlar qo'shadigan qo'shimcha.", "link": "https://modrinth.com/mod/delightful"},
        ],
    },
    "qurilish": {
        "title": "🏠 Bino qurish va Dekorativ",
        "mods": [
            {"name": "Chisel", "desc": "Bloklarni bezash uchun yuzlab yangi dekorativ variantlarni qo'shadi.", "link": "https://www.curseforge.com/minecraft/mc-mods/chisel"},
            {"name": "MrCrayfish's Furniture Mod", "desc": "Uy jihozlari — stul, stol, televizor va boshqalarni qo'shadi.", "link": "https://www.curseforge.com/minecraft/mc-mods/mrcrayfishs-furniture-mod"},
            {"name": "Macaw's Furniture", "desc": "Ko'plab uslubdagi mebel bloklarini qo'shadi.", "link": "https://modrinth.com/mod/macaws-furniture"},
            {"name": "Macaw's Bridges", "desc": "Turli uslubdagi ko'priklarni qurish imkonini beradi.", "link": "https://modrinth.com/mod/macaws-bridges"},
            {"name": "Macaw's Doors", "desc": "Ko'plab yangi eshik dizaynlarini qo'shadi.", "link": "https://modrinth.com/mod/macaws-doors"},
            {"name": "Macaw's Windows", "desc": "Turli xil deraza va panjara bloklarini qo'shadi.", "link": "https://modrinth.com/mod/macaws-windows"},
            {"name": "Chipped", "desc": "Chisel modiga qo'shimcha bo'lib, yanada ko'proq dekorativ bloklar beradi.", "link": "https://modrinth.com/mod/chipped"},
            {"name": "Quark", "desc": "Vanilla uslubida ko'plab kichik-kichik foydali va bezakli qo'shimchalarni qo'shadi.", "link": "https://www.curseforge.com/minecraft/mc-mods/quark"},
        ],
    },
    "telefon_bedrock": {
        "title": "📱 Telefon (Bedrock/Pocket Edition) uchun",
        "mods": [
            {
                "name": "MCPEDL — Bedrock Addonlar",
                "desc": "Yuqoridagi modlarning aksariyati faqat KOMPYUTER (Java Edition) uchun ishlaydi. Telefonda (Bedrock/Pocket Edition) o'ynasangiz, ular o'rniga \"Add-on\" deb ataladigan boshqa turdagi qo'shimchalar kerak. MCPEDL — bunday addon va texturalarning eng katta, ishonchli manbasi.",
                "link": "https://mcpedl.com",
            },
            {
                "name": "Minecraft Marketplace",
                "desc": "Mojang'ning rasmiy do'koni — telefon ilovasi ichidan to'g'ridan-to'g'ri xarid qilib o'rnatiladigan rasmiy addon, teri va dunyolar.", 
                "link": "https://www.minecraft.net/en-us/marketplace",
            },
        ],
    },
}
